CREATE DATABASE tracker;

use tracker;

CREATE TABLE diary (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	food VARCHAR(30) NOT NULL,
	serving INT(50) NOT NULL,
	kcal INT(30),
    meal VARCHAR(100),
	date TIMESTAMP
);

CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);